### ISSUE TITLE
yaml: unmarshal errors - mapping key "<<" already defined

### ISSUE THREAD

**Issue by floodcontrol** [P2Enjoy/kohya_ss-docker#15]
Had issue with docker-compose.yaml mapping keys.

I replaced 

`  kohya: &kohya_service
    <<: *base_service \n
    <<: *gpu_service
    <<: *kohya_service_envs`

with

`  kohya: &kohya_service
    <<: [*base_service, *gpu_service, *kohya_service_envs]`

and 

`  kohya_debug:
    <<: *kohya_service
    <<: *kohya_service_envs`

with 

` kohya_debug:
    <<: [*kohya_service, *kohya_service_envs]`

Which seemed to resolve the issue.

**Comment by martinobettucci** [comment]
Thanks! I didn't know that kind of include syntax 😉
I'll merge it in the next update

**Comment by matbee-eth** [comment]
I get: `mapping values are not allowed in this context` with that fix

**Comment by junwen-k** [comment]
@matbee-eth The updated `docker-compose.yml` should be like this:

```yaml
...

services:

  kohya: &kohya_service
    <<: [*base_service, *gpu_service, *kohya_service_envs]
    profiles: ["kohya"]
    environment: 
      - TF_ENABLE_ONEDNN_OPTS=1
      - XDG_CACHE_HOME=/data/.cache
      - ACCELERATE=False
      - DISPLAY=unix$DISPLAY
      - RUN_ARGS=/koyah_ss/kohya_gui.py --listen 0.0.0.0 --server_port 7680
      #- RUN_ARGS=/koyah_ss/lora_gui.py
      - RUNNER=/docker/run.sh
      
  kohya_debug:
    <<: [*kohya_service, *kohya_service_envs]
    profiles: ["kohya_debug"]
    stdin_open: true
    tty: true
    environment:
      - RUNNER=/docker/debug.sh
```
